export const SNAPCALL_CALL_ENDED = 'widget/talk/SNAPCALL_CALL_ENDED'
export const SNAPCALL_CALL_STARTED = 'widget/talk/SNAPCALL_CALL_STARTED'
export const SNAPCALL_CALL_CONNECTED = 'widget/talk/SNAPCALL_CALL_CONNECTED'
export const SNAPCALL_TIMER_UPDATED = 'widget/talk/SNAPCALL_TIMER_UPDATED'
export const SNAPCALL_CALL_ENDED_NOTIFICATION_CLOSED =
  'widget/talk/SNAPCALL_CALL_ENDED_NOTIFICATION_CLOSED'
export const SET_SNAPCALL_SUPPORTED = 'widget/talk/SET_SNAPCALL_SUPPORTED'
export const SNAPCALL_CALL_FAILED = 'widget/talk/SNAPCALL_CALL_FAILED'
export const SNAPCALL_CALL_FAILED_NOTIFICATION_CLOSED =
  'widget/talk/SNAPCALL_CALL_FAILED_NOTIFICATION_CLOSED'
export const SNAPCALL_CALL_DISCONNECTED = 'widget/talk/SNAPCALL_CALL_DISCONNECTED'
export const SNAPCALL_CALL_DISCONNECTED_NOTIFICATION_CLOSED =
  'widget/talk/SNAPCALL_CALL_DISCONNECTED_NOTIFICATION_CLOSED'
