export const SNAPCALL_CALL_ENDED = 'widget/talk/SNAPCALL_CALL_ENDED'
export const SNAPCALL_CALL_STARTED = 'widget/talk/SNAPCALL_CALL_STARTED'
export const SNAPCALL_CALL_CONNECTED = 'widget/talk/SNAPCALL_CALL_CONNECTED'
export const SNAPCALL_TIMER_UPDATED = 'widget/talk/SNAPCALL_TIMER_UPDATED'
export const SNAPCALL_CALL_ENDED_NOTIFICATION_CLOSED =
  'widget/talk/SNAPCALL_CALL_ENDED_NOTIFICATION_CLOSED'
export const SET_SNAPCALL_SUPPORTED = 'widget/talk/SET_SNAPCALL_SUPPORTED'
