export const MICROPHONE_MUTED = 'widget/talk/MICROPHONE_MUTED'
export const MICROPHONE_UNMUTED = 'widget/talk/MICROPHONE_UNMUTED'
export const RECORDING_CONSENT_DENIED = 'widget/talk/RECORDING_CONSENT_DENIED'
export const RECORDING_CONSENT_ACCEPTED = 'widget/talk/RECORDING_CONSENT_ACCEPTED'
export const END_CALL = 'widget/talk/END_CALL'
export const START_CALL = 'widget/talk/START_CALL'
export const INCREMENT_CALL_TIMER = 'widget/talk/INCREMENT_CALL_TIMER'
