export const MICROPHONE_MUTED = 'widget/talk/MICROPHONE_MUTED'
export const MICROPHONE_UNMUTED = 'widget/talk/MICROPHONE_UNMUTED'
export const RECORDING_CONSENT_DENIED = 'widget/talk/RECORDING_CONSENT_DENIED'
export const RECORDING_CONSENT_ACCEPTED = 'widget/talk/RECORDING_CONSENT_ACCEPTED'
