export default {
  home: () => '/talk',
  online: () => '/talk/online',
  offline: () => '/talk/offline',
  callbackOnly: () => '/talk/online/callback_only',
  phoneOnly: () => '/talk/online/phone_only',
  callbackAndPhone: () => '/talk/online/callback_and_phone',
  clickToCall: () => '/talk/online/click_to_call',
  clickToCallPermissions: () => '/talk/online/click_to_call/permissions',
  clickToCallConsent: () => '/talk/online/click_to_call/consent',
  clickToCallInProgress: () => '/talk/online/click_to_call/in_progress',
  clickToCallNetworkError: () => '/talk/online/click_to_call/network_error',
  successNotification: () => '/talk/success_notification',
  clickToCallPermissionsDenied: () => '/talk/online/click_to_call/microphone_permissions_denied',
}
