export const QUESTION_VALUE_CHANGED = 'widget/answerBot/QUESTION_VALUE_CHANGED';

export const QUESTION_SUBMITTED_PENDING = 'widget/answerBot/QUESTION_SUBMITTED_PENDING';
export const QUESTION_SUBMITTED_FULFILLED = 'widget/answerBot/QUESTION_SUBMITTED_FULFILLED';
export const QUESTION_SUBMITTED_REJECTED = 'widget/answerBot/QUESTION_SUBMITTED_REJECTED';

export const CONVERSATION_SCROLL_CHANGED = 'widget/answerBot/CONVERSATION_SCROLL_CHANGED';
export const CONVERSATION_SCREEN_CLOSED = 'widget/answerBot/CONVERSATION_SCREEN_CLOSED';
