export const RECEIVE_DEFERRED_CHAT_STATUS = 'widget/chat/RECEIVE_DEFERRED_CHAT_STATUS'
export const DEFER_CHAT_SETUP = 'widget/chat/DEFER_CHAT_SETUP'
export const BEGIN_CHAT_SETUP = 'widget/chat/BEGIN_CHAT_SETUP'
export const EMAIL_TRANSCRIPT_REQUEST_SENT = 'widget/chat/EMAIL_TRANSCRIPT_REQUEST_SENT'
export const EMAIL_TRANSCRIPT_SUCCESS = 'widget/chat/EMAIL_TRANSCRIPT_SUCCESS'
export const EMAIL_TRANSCRIPT_FAILURE = 'widget/chat/EMAIL_TRANSCRIPT_FAILURE'

export const UPDATE_CHAT_MENU_VISIBILITY = 'widget/chat/UPDATE_CHAT_MENU_VISIBILITY'
