export const SESSION_STARTED = 'widget/answerBot/SESSION_STARTED'

export const SESSION_RESOLVED_PENDING = 'widget/answerBot/SESSION_RESOLVED_PENDING'
export const SESSION_RESOLVED_REJECTED = 'widget/answerBot/SESSION_RESOLVED_REJECTED'
export const SESSION_RESOLVED_FULFILLED = 'widget/answerBot/SESSION_RESOLVED_FULFILLED'

export const SESSION_FALLBACK = 'widget/answerBot/SESSION_FALLBACK'

export const SESSION_AUTO_SCROLL = 'widget/answerBot/SESSION_AUTO_SCROLL'
