export const ARTICLE_DISMISSED_PENDING = 'widget/answerBot/ARTICLE_DISMISSED_PENDING';
export const ARTICLE_DISMISSED_FULFILLED = 'widget/answerBot/ARTICLE_DISMISSED_FULFILLED';
export const ARTICLE_DISMISSED_REJECTED = 'widget/answerBot/ARTICLE_DISMISSED_REJECTED';

export const ARTICLE_VIEWED_PENDING = 'widget/answerBot/ARTICLE_VIEWED_PENDING';
export const ARTICLE_VIEWED_FULFILLED = 'widget/answerBot/ARTICLE_VIEWED_FULFILLED';
export const ARTICLE_VIEWED_REJECTED = 'widget/answerBot/ARTICLE_VIEWED_REJECTED';
