import _ from 'lodash';

export const countriesByIso = {
  'AD': { code: '376', name: 'Andorra' },
  'AE': { code: '971', name: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)' },
  'AF': { code: '93', name: 'Afghanistan (‫افغانستان‬‎)' },
  'AG': { code: '1', name: 'Antigua and Barbuda' },
  'AI': { code: '1', name: 'Anguilla' },
  'AL': { code: '355', name: 'Albania (Shqipëri)' },
  'AM': { code: '374', name: 'Armenia (Հայաստան)' },
  'AN': { code: '599', name: 'Netherlands Antilles' },
  'AO': { code: '244', name: 'Angola' },
  'AQ': { code: '672', name: 'Antarctica' },
  'AR': { code: '54', name: 'Argentina' },
  'AS': { code: '1', name: 'American Samoa' },
  'AT': { code: '43', name: 'Austria (Österreich)' },
  'AU': { code: '61', name: 'Australia' },
  'AW': { code: '297', name: 'Aruba' },
  'AZ': { code: '994', name: 'Azerbaijan (Azərbaycan)' },
  'BA': { code: '387', name: 'Bosnia and Herzegovina (Босна и Херцеговина)' },
  'BB': { code: '1', name: 'Barbados' },
  'BD': { code: '880', name: 'Bangladesh (বাংলাদেশ)' },
  'BE': { code: '32', name: 'Belgium (België)' },
  'BF': { code: '226', name: 'Burkina Faso' },
  'BG': { code: '359', name: 'Bulgaria (България)' },
  'BH': { code: '973', name: 'Bahrain (‫البحرين‬‎)' },
  'BI': { code: '257', name: 'Burundi (Uburundi)' },
  'BJ': { code: '229', name: 'Benin (Bénin)' },
  'BL': { code: '590', name: 'Saint Barthélemy' },
  'BM': { code: '1', name: 'Bermuda' },
  'BN': { code: '673', name: 'Brunei' },
  'BO': { code: '591', name: 'Bolivia' },
  'BR': { code: '55', name: 'Brazil' },
  'BS': { code: '1', name: 'Bahamas' },
  'BT': { code: '975', name: 'Bhutan (འབྲུག)' },
  'BW': { code: '267', name: 'Botswana' },
  'BY': { code: '375', name: 'Belarus (Беларусь)' },
  'BZ': { code: '501', name: 'Belize' },
  'CA': { code: '1', name: 'Canada' },
  'CC': { code: '61', name: 'Cocos Islands' },
  'CD': { code: '243', name: 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)' },
  'CF': { code: '236', name: 'Central African Republic (République centrafricaine)' },
  'CG': { code: '242', name: 'Republic of the Congo' },
  'CH': { code: '41', name: 'Switzerland (Schweiz)' },
  'CI': { code: '225', name: 'Ivory Coast' },
  'CK': { code: '682', name: 'Cook Islands' },
  'CL': { code: '56', name: 'Chile' },
  'CM': { code: '237', name: 'Cameroon (Cameroun)' },
  'CN': { code: '86', name: 'China (中国)' },
  'CO': { code: '57', name: 'Colombia' },
  'CR': { code: '506', name: 'Costa Rica' },
  'CU': { code: '53', name: 'Cuba' },
  'CV': { code: '238', name: 'Cape Verde (Kabu Verdi)' },
  'CW': { code: '599', name: 'Curacao' },
  'CX': { code: '61', name: 'Christmas Island' },
  'CY': { code: '357', name: 'Cyprus (Κύπρος)' },
  'CZ': { code: '420', name: 'Czech Republic' },
  'DE': { code: '49', name: 'Germany (Deutschland)' },
  'DJ': { code: '253', name: 'Djibouti' },
  'DK': { code: '45', name: 'Denmark (Danmark)' },
  'DM': { code: '1', name: 'Dominica' },
  'DO': { code: '1', name: 'Dominican Republic (República Dominicana)' },
  'DZ': { code: '213', name: 'Algeria (‫الجزائر‬‎)' },
  'EC': { code: '593', name: 'Ecuador' },
  'EE': { code: '372', name: 'Estonia (Eesti)' },
  'EG': { code: '20', name: 'Egypt (‫مصر‬‎)' },
  'EH': { code: '212', name: 'Western Sahara (‫الصحراء الغربية‬‎)' },
  'ER': { code: '291', name: 'Eritrea' },
  'ES': { code: '34', name: 'Spain (España)' },
  'ET': { code: '251', name: 'Ethiopia' },
  'FI': { code: '358', name: 'Finland' },
  'FJ': { code: '679', name: 'Fiji' },
  'FK': { code: '500', name: 'Falkland Islands (Islas Malvinas)' },
  'FM': { code: '691', name: 'Micronesia' },
  'FO': { code: '298', name: 'Faroe Islands (Føroyar)' },
  'FR': { code: '33', name: 'France' },
  'GA': { code: '241', name: 'Gabon' },
  'GB': { code: '44', name: 'United Kingdom' },
  'GD': { code: '1', name: 'Grenada' },
  'GE': { code: '995', name: 'Georgia (საქართველო)' },
  'GG': { code: '44', name: 'Guernsey' },
  'GH': { code: '233', name: 'Ghana (Gaana)' },
  'GI': { code: '350', name: 'Gibraltar' },
  'GL': { code: '299', name: 'Greenland (Kalaallit Nunaat)' },
  'GM': { code: '220', name: 'Gambia' },
  'GN': { code: '224', name: 'Guinea (Guinée)' },
  'GQ': { code: '240', name: 'Equatorial Guinea (Guinea Ecuatorial)' },
  'GR': { code: '30', name: 'Greece (Ελλάδα)' },
  'GT': { code: '502', name: 'Guatemala' },
  'GU': { code: '1', name: 'Guam' },
  'GW': { code: '245', name: 'Guinea-Bissau (Guiné Bissau)' },
  'GY': { code: '592', name: 'Guyana' },
  'HK': { code: '852', name: 'Hong Kong (香港)' },
  'HN': { code: '504', name: 'Honduras' },
  'HR': { code: '385', name: 'Croatia (Hrvatska)' },
  'HT': { code: '509', name: 'Haiti' },
  'HU': { code: '36', name: 'Hungary (Magyarország)' },
  'ID': { code: '62', name: 'Indonesia' },
  'IE': { code: '353', name: 'Ireland' },
  'IL': { code: '972', name: 'Israel (‫ישראל‬‎)' },
  'IM': { code: '44', name: 'Isle of Man' },
  'IN': { code: '91', name: 'India (भारत)' },
  'IO': { code: '246', name: 'British Indian Ocean Territory' },
  'IQ': { code: '964', name: 'Iraq (‫العراق‬‎)' },
  'IR': { code: '98', name: 'Iran (‫ایران‬‎)' },
  'IS': { code: '354', name: 'Iceland (Ísland)' },
  'IT': { code: '39', name: 'Italy' },
  'JE': { code: '44', name: 'Jersey' },
  'JM': { code: '1', name: 'Jamaica' },
  'JO': { code: '962', name: 'Jordan (‫الأردن‬‎)' },
  'JP': { code: '81', name: 'Japan (日本)' },
  'KE': { code: '254', name: 'Kenya' },
  'KG': { code: '996', name: 'Kyrgyzstan (Кыргызстан)' },
  'KH': { code: '855', name: 'Cambodia (កម្ពុជា)' },
  'KI': { code: '686', name: 'Kiribati' },
  'KM': { code: '269', name: 'Comoros (‫جزر القمر‬‎)' },
  'KN': { code: '1', name: 'Saint Kitts and Nevis' },
  'KP': { code: '850', name: 'North Korea (조선 민주주의 인민 공화국)' },
  'KR': { code: '82', name: 'South Korea (대한민국)' },
  'KW': { code: '965', name: 'Kuwait (‫الكويت‬‎)' },
  'KY': { code: '1', name: 'Cayman Islands' },
  'KZ': { code: '7', name: 'Kazakhstan (Казахстан)' },
  'LA': { code: '856', name: 'Laos (ລາວ)' },
  'LB': { code: '961', name: 'Lebanon (‫لبنان‬‎)' },
  'LC': { code: '1', name: 'Saint Lucia' },
  'LI': { code: '423', name: 'Liechtenstein' },
  'LK': { code: '94', name: 'Sri Lanka (ශ්‍රී ලංකාව)' },
  'LR': { code: '231', name: 'Liberia' },
  'LS': { code: '266', name: 'Lesotho' },
  'LT': { code: '370', name: 'Lithuania (Lietuva)' },
  'LU': { code: '352', name: 'Luxembourg' },
  'LV': { code: '371', name: 'Latvia (Latvija)' },
  'LY': { code: '218', name: 'Libya (‫ليبيا‬‎)' },
  'MA': { code: '212', name: 'Morocco (‫المغرب‬‎)' },
  'MC': { code: '377', name: 'Monaco' },
  'MD': { code: '373', name: 'Moldova (Republica Moldova)' },
  'ME': { code: '382', name: 'Montenegro (Crna Gora)' },
  'MF': { code: '590', name: 'Saint Martin' },
  'MG': { code: '261', name: 'Madagascar (Madagasikara)' },
  'MH': { code: '692', name: 'Marshall Islands' },
  'MK': { code: '389', name: 'Macedonia' },
  'ML': { code: '223', name: 'Mali' },
  'MM': { code: '95', name: 'Myanmar (Burma) (မြန်မာ)' },
  'MN': { code: '976', name: 'Mongolia (Монгол)' },
  'MO': { code: '853', name: 'Macau (澳門)' },
  'MP': { code: '1', name: 'Northern Mariana Islands' },
  'MR': { code: '222', name: 'Mauritania (‫موريتانيا‬‎)' },
  'MS': { code: '1', name: 'Montserrat' },
  'MT': { code: '356', name: 'Malta' },
  'MU': { code: '230', name: 'Mauritius (Moris)' },
  'MV': { code: '960', name: 'Maldives' },
  'MW': { code: '265', name: 'Malawi' },
  'MX': { code: '52', name: 'Mexico (México)' },
  'MY': { code: '60', name: 'Malaysia' },
  'MZ': { code: '258', name: 'Mozambique (Moçambique)' },
  'NA': { code: '264', name: 'Namibia (Namibië)' },
  'NC': { code: '687', name: 'New Caledonia (Nouvelle-Calédonie)' },
  'NE': { code: '227', name: 'Niger (Nijar)' },
  'NG': { code: '234', name: 'Nigeria' },
  'NI': { code: '505', name: 'Nicaragua' },
  'NL': { code: '31', name: 'Netherlands (Nederland)' },
  'NO': { code: '47', name: 'Norway (Norge)' },
  'NP': { code: '977', name: 'Nepal (नेपाल)' },
  'NR': { code: '674', name: 'Nauru' },
  'NU': { code: '683', name: 'Niue' },
  'NZ': { code: '64', name: 'New Zealand' },
  'OM': { code: '968', name: 'Oman (‫عُمان‬‎)' },
  'PA': { code: '507', name: 'Panama (Panamá)' },
  'PE': { code: '51', name: 'Peru (Perú)' },
  'PF': { code: '689', name: 'French Polynesia (Polynésie française)' },
  'PG': { code: '675', name: 'Papua New Guinea' },
  'PH': { code: '63', name: 'Philippines' },
  'PK': { code: '92', name: 'Pakistan (‫پاکستان‬‎)' },
  'PL': { code: '48', name: 'Poland (Polska)' },
  'PM': { code: '508', name: 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon' },
  'PN': { code: '64', name: 'Pitcairn' },
  'PR': { code: '1', name: 'Puerto Rico' },
  'PS': { code: '970', name: 'Palestine (‫فلسطين‬‎)' },
  'PT': { code: '351', name: 'Portugal' },
  'PW': { code: '680', name: 'Palau' },
  'PY': { code: '595', name: 'Paraguay' },
  'QA': { code: '974', name: 'Qatar (‫قطر‬‎)' },
  'RE': { code: '262', name: 'Réunion (La Réunion)' },
  'RO': { code: '40', name: 'Romania (România)' },
  'RS': { code: '381', name: 'Serbia (Србија)' },
  'RU': { code: '7', name: 'Russia (Россия)' },
  'RW': { code: '250', name: 'Rwanda' },
  'SA': { code: '966', name: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)' },
  'SB': { code: '677', name: 'Solomon Islands' },
  'SC': { code: '248', name: 'Seychelles' },
  'SD': { code: '249', name: 'Sudan (‫السودان‬‎)' },
  'SE': { code: '46', name: 'Sweden (Sverige)' },
  'SG': { code: '65', name: 'Singapore' },
  'SH': { code: '290', name: 'Saint Helena' },
  'SI': { code: '386', name: 'Slovenia (Slovenija)' },
  'SJ': { code: '47', name: 'Svalbard and Jan Mayen' },
  'SK': { code: '421', name: 'Slovakia (Slovensko)' },
  'SL': { code: '232', name: 'Sierra Leone' },
  'SM': { code: '378', name: 'San Marino' },
  'SN': { code: '221', name: 'Senegal (Sénégal)' },
  'SO': { code: '252', name: 'Somalia (Soomaaliya)' },
  'SR': { code: '597', name: 'Suriname' },
  'SS': { code: '211', name: 'South Sudan (‫جنوب السودان‬‎)' },
  'ST': { code: '239', name: 'São Tomé and Príncipe (São Tomé e Príncipe)' },
  'SV': { code: '503', name: 'El Salvador' },
  'SX': { code: '1', name: 'Sint Maarten' },
  'SY': { code: '963', name: 'Syria (‫سوريا‬‎)' },
  'SZ': { code: '268', name: 'Swaziland' },
  'TC': { code: '1', name: 'Turks and Caicos Islands' },
  'TD': { code: '235', name: 'Chad' },
  'TG': { code: '228', name: 'Togo' },
  'TH': { code: '66', name: 'Thailand (ไทย)' },
  'TJ': { code: '992', name: 'Tajikistan' },
  'TK': { code: '690', name: 'Tokelau' },
  'TL': { code: '670', name: 'East Timor' },
  'TM': { code: '993', name: 'Turkmenistan' },
  'TN': { code: '216', name: 'Tunisia (‫تونس‬‎)' },
  'TO': { code: '676', name: 'Tonga' },
  'TR': { code: '90', name: 'Turkey (Türkiye)' },
  'TT': { code: '1', name: 'Trinidad and Tobago' },
  'TV': { code: '688', name: 'Tuvalu' },
  'TW': { code: '886', name: 'Taiwan (台灣)' },
  'TZ': { code: '255', name: 'Tanzania' },
  'UA': { code: '380', name: 'Ukraine (Україна)' },
  'UG': { code: '256', name: 'Uganda' },
  'US': { code: '1', name: 'United States' },
  'UY': { code: '598', name: 'Uruguay' },
  'UZ': { code: '998', name: 'Uzbekistan (Oʻzbekiston)' },
  'VA': { code: '379', name: 'Vatican' },
  'VC': { code: '1', name: 'Saint Vincent and the Grenadines' },
  'VE': { code: '58', name: 'Venezuela' },
  'VG': { code: '1', name: 'British Virgin Islands' },
  'VI': { code: '1', name: 'U.S. Virgin Islands' },
  'VN': { code: '84', name: 'Vietnam (Việt Nam)' },
  'VU': { code: '678', name: 'Vanuatu' },
  'WF': { code: '681', name: 'Wallis and Futuna (Wallis-et-Futuna)' },
  'WS': { code: '685', name: 'Samoa' },
  'XK': { code: '383', name: 'Kosovo' },
  'YE': { code: '967', name: 'Yemen (‫اليمن‬‎)' },
  'YT': { code: '262', name: 'Mayotte' },
  'ZA': { code: '27', name: 'South Africa' },
  'ZM': { code: '260', name: 'Zambia' },
  'ZW': { code: '263', name: 'Zimbabwe' }
};

export const countriesByName = _.reduce(countriesByIso, (result, value, key) => {
  result[value.name] = { code: value.code, iso: key };
  return result;
}, {});
