#!/bin/sh

set -e

webDriverBrewPackages=(cairo imagemagick graphicsmagick selenium-server-standalone chromedriver)

heading() {
  echo "$1... \c";
}

bold() {
  echo "\033[1m$1\033[0m"
}

pass() {
  bold "DONE"
}

fail() {
  bold "FAIL"
  echo
}

fail_and_exit() {
  fail
  exit -1
}

try() {
  heading "$1"
  if eval "$2"
  then
    pass
  else
    fail_and_exit
  fi
}

try "Installing gulp, bower" "npm install -g --quiet gulp bower > /dev/null"
try "Installing npm & bower packages" "npm install --quiet > /dev/null && bower install --quiet > /dev/null"
try "Building Engagement Framework" "gulp build-dev > /dev/null"
try "Setting up pre-commit hooks" "ln -s ../../script/pre-commit .git/hooks/pre-commit > /dev/null && chmod +x .git/hooks/pre-commit < /dev/null"
try "Downloading translations" "script/fetch_i18n"
bold "Installing UI Regression Tooling"

for pkg in ${webDriverBrewPackages[@]}; do
  if brew list -1 | grep -q "^${pkg}"; then
    bold "'$pkg' is already installed"
  else
    try "Installing $pkg" "brew install $pkg"
  fi
done

try "Installing webdriverio & webdrivercss" "PKG_CONFIG_PATH=\"/opt/X11/lib/pkgconfig\" npm install webdrivercss webdriverio --quiet > /dev/null"

echo
bold "All systems are go!"
