#!/bin/sh

set -e

heading() {
  echo "$1... \c";
}

bold() {
  echo "\033[1m$1\033[0m"
}

pass() {
  bold "DONE"
}

fail() {
  bold "FAIL"
  echo
}

fail_and_exit() {
  fail
  exit -1
}

try() {
  heading "$1"
  if eval "$2"
  then
    pass
  else
    fail_and_exit
  fi
}

try "Installing npm packages" "npm install --quiet > /dev/null"
try "Installing ruby gems" "bundle install --quiet"
try "Downloading translations" "script/fetch_i18n"
try "Building Engagement Framework" "npm run build"
try "Preparing template files" "script/setup_html_templates.rb"

echo
bold "All systems are go!"
