#!/bin/sh

set -e

heading() {
  echo "$1... \c";
}

bold() {
  echo "\033[1m$1\033[0m"
}

pass() {
  bold "DONE"
}

fail() {
  bold "FAIL"
  echo
}

fail_and_exit() {
  fail
  exit -1
}

try() {
  heading "$1"
  if eval "$2"
  then
    pass
  else
    fail_and_exit
  fi
}

try "Preparing node, nvm and npm packages" "script/setup_node_env"
try "Installing ruby gems" "bundle install --quiet"
try "Building Embeddable Framework" "yarn workspace @zendesk/embeddable-framework build"
try "Preparing template files" "cd ./packages/framework && ./script/setup_html_templates.rb"

echo
bold "All systems are go!"
