/* jshint ignore: start */

// jscs:disable requireSpaceAfterBinaryOperators, maximumLineLength
export var stopWords = [
  'a','am','an','and','any','are','as','at',
  'b','be','but','by',
  'c','can','cannot','can\'t','could','couldn\'t',
  'd','did','didn\'t','do','does','doesn\'t','don\'t',
  'e','each','end','ended','ending','ends','enough','even','evenly','ever',
  'f','far','few','for',
  'g','get','gets','go','going','good','goods','got',
  'h','had','hadn\'t','has','hasn\'t','have','haven\'t','having','he','he\'d',
  'he\'ll','her','here','here\'s','hers','he\'s','him','his','how','however','how\'s',
  'i','i\'d','if','i\'ll','i\'m','in','is','isn\'t','it','its',
  'it\'s','itself','i\'ve','j','just',
  'k','keep','keeps','knew','know','known','knows','l','let','lets','let\'s','like','likely',
  'm','many','may','me','might','more','most','mostly','mr','mrs','much','must','mustn\'t',
  'my','myself','n','next','no','non','noone','nor','not',
  'o','of','often','only','or','ought','our','ours','ourselves','out','own',
  'p','per','perhaps','possible','put','puts',
  'q',
  'r','rather','really','right',
  's','said','same','saw','say','says','see','seem','seemed','seeming','seems',
  'sees','shall','shan\'t','she','she\'d','she\'ll','she\'s','should','shouldn\'t',
  'so','some','still','such','sure',
  't','than','that','that\'s','the','their','theirs','them','themselves','then',
  'there','therefore','there\'s','these','they','they\'d','they\'ll','they\'re','they\'ve',
  'this','those','though','thought','thoughts','through','thus','to','too','took',
  'u','up','upon','us','use','used','uses',
  'v','very',
  'w','want','wanted','wanting','wants','was','wasn\'t','way','ways','we','we\'d',
  'well','we\'ll','wells','went','were','we\'re','weren\'t','we\'ve','what','what\'s',
  'when','when\'s','where','where\'s','whether','which','while','who','whole','whom',
  'who\'s','whose','why','why\'s','will','with','within','without','won\'t','would','wouldn\'t',
  'x',
  'y','year','years','yes','yet','you','you\'d','you\'ll','your','you\'re','yours',
  'yourself','yourselves','you\'ve',
  'z'
];
// jscs:enable
