name: samson

on:
  push:
    branches: master

jobs:
  samson:
    runs-on: zendesk-stable
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Notify Samson
      env:
        WEBHOOK_URL: 'https://samson.zende.sk/integrations/travis/b127503546dbc459293e47fbae026af2'
        COMMIT: ${{ github.sha }}
      uses: zendesk/ga/samson-create-release@v1
