export const WIDGET_CLOSED_EVENT = 'WIDGET_CLOSED_EVENT';
export const WIDGET_OPENED_EVENT = 'WIDGET_OPENED_EVENT';

export const CHAT_CONNECTED_EVENT = 'CHAT_CONNECTED_EVENT';
export const CHAT_ENDED_EVENT = 'CHAT_ENDED_EVENT';
export const CHAT_STARTED_EVENT = 'CHAT_STARTED_EVENT';
export const CHAT_STATUS_EVENT = 'CHAT_STATUS_EVENT';
export const CHAT_UNREAD_MESSAGES_EVENT = 'CHAT_UNREAD_MESSAGES_EVENT';
export const CHAT_DEPARTMENT_STATUS_EVENT = 'CHAT_DEPARTMENT_STATUS_EVENT';
